### ISSUE TITLE
Help wanted: Own tests or promises-tests tests?

### ISSUE THREAD

**Issue by bucaran** [promises-aplus/promises-tests#70]
I am writing a Promises A+ implementation (just for fun and in order to understand promises better), but I don't understand what is the purpose of writing my own tests _VS_ using `promises-aplus/promises-tests` or even both. I see some implementations write their own tests, but isn't it enough to make `promises-tests` pass? I would like to know if I am missing something. 

Cheers.

**Comment by briancavalier** [comment]
@bucaran It depends on what you mean by "suffice" :)  Passing the tests in this repo means that you have a Promises/A+ compliant implementation of the `.then()` method, and you can display the Promises/A+ logo in your README.  You can also send a PR to have your impl listed on the [implementations page](https://promisesaplus.com/implementations)

If that's your goal, then passing making `promises-tests` pass is all you really need.  However, since Promises/A+ is a very minimal spec, focused only on `then`, most other libraries include more tests simply because they provide more features/APIs than just `then()`.

Make sense?

**Comment by bucaran** [comment]
Clear and sound. 

This

> Passing the tests in this repo means that you have a Promises/A+ compliant implementation of the .then() method, and you can display the Promises/A+ logo in your README. You can also send a PR to have your impl listed on the implementations page

Would be a nice thing to add to the main README before the _How To Run_ header.

**Comment by briancavalier** [comment]
I like that idea @bucaran.  @Domenic, what do you think?

**Comment by domenic** [comment]
Agreed!
